language: bash
install: bash install.sh
script: STATUS=$(curl -I localhost &> /dev/stderr --write-out "%{http_code}") | if
  test $STATUS 200; then exit 0; fi
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: bookwebsite222252 
  on:
    branch: main
  cleanup: false
env:
  global:
  - secure: DOI1r9Ob+gaYLy9eX6zec2hc/I1ZLs8KvZSKpKQxnlGYOJr3VrkdK79NC+CUJzUJPN+mHqvZYo5lTK1Q0PKbH2fXK+BKSDqaE7pes22xd/BztifWy/7ja8zLF0AafiepTddLpKW/YrhtO9ygiP29M8/ejCjE9EsuLGvdi0ZPsyRf8InTZ4dWzNzhZ+mPCucFEBVSW0EZ/XRHFqlq2MgeNoJygHBi3/8UwSXSljXGQUJU85dWHARx7UK7R8plHlvChG7bnnWBKqCzoHg8a+07/Js9li7r3reNRnH397awcMLn7Am7GJ7Q/8EBhrNk3UCNYl+ELvRp+hsiayLcxxH/4jehM/ZT1WdxGIbiiQfiSynNtMEc2AMLlsIVy/j9/h4dFIWWHMeatnZMY4iTl7Oj13z/CxkQsJH78/V6GHXmS9xda4FIT+I03tDAxOsrUM0Md5DE3ko25/2u5vq23Bs0BEoQbL/8o8+f46rwVc5q93qTDRJjZR0o2X8bhB+8aK+BcaiBCiMiwFiT8qJ/SlbreV9qPGP8YjF7dzXrofWV6tFqibUMgI5EXeeYGi8DezOM5pZIVgFf45UAc9vM9AtLy7As96k7a8zA1qcqPUEwKPu9bqV+KSnRgskWg+B4fEvJRJWXtDYpG4NqrxHyP9DFgTQ+idgIykn3uvYnMAyC69w=
  - secure: KE4pLesZddp1nujOQ+6IG67W0cy0bsloapXYTy3P82fFZ8JeE9joo9Gerbr5nDw1YmRCSIyKKIkhk78Il+hZIca43kH8OcXVNmQyhpI8dC9BYvqaIR3UqxKbd1QWvKkCpPJ/BF09pxPACq+oJeRebb/cNqc/c+HouH7xaAA4eJD13AvJvHPB7Y36ItFzWllVl7QMNEFBRRKV1NozEXQZnCiWhA9AHAo/RNzaE8Nztbwr+Aaq1jlkoAvYpdtUFnt+paUtfV8MKw8LNMQZsbDNqcX4d6bq9AzmHZrh085ic/E0wPUB+ZzuY6KA1L5mm2b8107o8tTE5D/yehiyQoWJ6zHqua3mnrbmbAysnODmridkZRYBtYlF9IawcmG0Zodbr8xReTlRqkSV1LDyumEnLFRI9pQCdC2XTu2aMc8BplQXYLtGO6b8k7smyYit/OIFVf8xOv4SufFeY5pszdNeziRcOVuZqfDKdl1xzwHs4E2bPEGeYmL80ILpDEygBu9TukV+TXzvSXb7GDine0uEwF7EZPDIL065TtRkp86owb5HE5r7TZtLuJ8dTDEBq5MaXQK9D5A8EJqSg7DqZ70mWc9EK+SC0DL+6FFEAYNRdKtH9ZXTyvFhk5vEmZrN19DmVvPKV9ih91HpLgOz0LZ5ZHP6crBtw2NcJUZ0NYiOj+8=
